---
title: Sebastián Terleira
description: Junior FullStack Web Developer, Escritor Técnico iniciante
domain: https://sebastianterleira.dev
language: es
repository: https://github.com/sebastianterleira/personal-site
email: seb.terleira1204@gmail.com
social:
  twitter: SebastianTerlei
  github: sebastianterleira
  linkedin: sebastianterleira
icon: /static/icon-website.png
navigation:
  - name: Bio
    path: /about/
incremental: false # Change to `true` if your server support keeping `.cache` and `public` folders
analytics: UA-138758078-1